按键背景: &key_bg
  type: original
  insets: { top: 6, left: 5, bottom: 6, right: 5 }
  normalColor: FCFCFE
  highlightColor: B7BCC4
  cornerRadius: 7
  normalLowerEdgeColor: 0000004D
  highlightLowerEdgeColor: 0000004D
  borderSize: 0.2
  normalBorderColor: 0000001A
  highlightBorderColor: 0000001A

按键上标前景样式: &ub
  fontSize: 0.88em
  center:
    y: 0.38
  normalColor: A7AEB9
  highlightColor: 000000

按键文字前景样式: &py
  fontSize: 0.75em
  center:
    y: 1.05
  normalColor: 000000
  highlightColor: 000000

keyboard:
  style: keyboardStyle
  subviews:
  - HStack:
      subviews:
      - Cell: hamsterButton
      - Cell: SwitcherButton
      - Cell: uploadButton
      - Cell: scriptButton
      - Cell: fileButton
  - HStack:
      subviews:
      - Cell: skinButton
      - Cell: 内嵌Button
      - Cell: soundsButton
      - Cell: backupButton
      - Cell: deployButton

floatTargetScale:
  x: 0.55
  y: 0.7

keyboardStyle:
  insets: {top: 8, left: 8, bottom: 8, right: 8}
  backgroundStyle: keyboardBackgroundStyle

keyboardBackgroundStyle:
  type: original
  normalColor: e2e4e9dd
  cornerRadius: 7
  borderSize: 0.4
  normalBorderColor: 22222255
  normalLowerEdgeColor: 00000055

hamsterButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - hamsterButtonForegroundStyle1
    - hamsterButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/main}

hamsterButtonForegroundStyle1:
  animation: animation
  systemImageName: keyboard
  <<: *ub

hamsterButtonForegroundStyle2:
  animation: animation
  text: 设置
  <<: *py

SwitcherButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - SwitcherButtonForegroundStyle1
    - SwitcherButtonForegroundStyle2
  action: {shortcutCommand: '#RimeSwitcher'}

SwitcherButtonForegroundStyle1:
  animation: animation
  systemImageName: switch.2
  <<: *ub

SwitcherButtonForegroundStyle2:
  animation: animation
  text: 方案
  <<: *py

uploadButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - uploadButtonForegroundStyle1
    - uploadButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/uploadInputSchema}

uploadButtonForegroundStyle1:
  animation: animation
  systemImageName: wifi
  <<: *ub

uploadButtonForegroundStyle2:
  animation: animation
  text: 上传
  <<: *py

soundsButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - soundsButtonForegroundStyle1
    - soundsButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/feedback}

soundsButtonForegroundStyle1:
  animation: animation
  systemImageName: speaker.wave.2
  <<: *ub

soundsButtonForegroundStyle2:
  animation: animation
  text: 声音
  <<: *py

scriptButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - scriptButtonForegroundStyle1
    - scriptButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/clipboard?type=script}

scriptButtonForegroundStyle1:
  animation: animation
  systemImageName: terminal
  <<: *ub

scriptButtonForegroundStyle2:
  animation: animation
  text: 脚本
  <<: *py

skinButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - skinButtonForegroundStyle1
    - skinButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/keyboardSkins}

skinButtonForegroundStyle1:
  animation: animation
  systemImageName: tshirt
  <<: *ub

skinButtonForegroundStyle2:
  animation: animation
  text: 皮肤
  <<: *py

内嵌Button:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - 内嵌ButtonForegroundStyle1
    - 内嵌ButtonForegroundStyle2
  action: {shortcutCommand: '#toggleEmbeddedInputMode'}

内嵌ButtonForegroundStyle1:
  animation: animation
  systemImageName: square.and.pencil
  <<: *ub

内嵌ButtonForegroundStyle2:
  animation: animation
  text: 内嵌
  <<: *py

fileButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - fileButtonForegroundStyle1
    - fileButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/finder}

fileButtonForegroundStyle1:
  animation: animation
  systemImageName: folder
  <<: *ub

fileButtonForegroundStyle2:
  animation: animation
  text: 文件
  <<: *py

backupButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - backupButtonForegroundStyle1
    - backupButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/backup}

backupButtonForegroundStyle1:
  animation: animation
  systemImageName: person.icloud
  <<: *ub

backupButtonForegroundStyle2:
  animation: animation
  text: 备份
  <<: *py

deployButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - deployButtonForegroundStyle1
    - deployButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/rime?deploy}

deployButtonForegroundStyle1:
  animation: animation
  systemImageName: arrow.2.circlepath
  <<: *ub

deployButtonForegroundStyle2:
  animation: animation
  text: 部署
  <<: *py

ButtonBackgroundStyle:
  animation: animation
  <<: *key_bg

animation:
  - type: bounds
    duration: 0.6 # 动画时长，单位毫秒
